package org.linhtk.orchestrator.model.knowledge;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import org.linhtk.common.model.AbstractAuditEntity;

import java.util.HashMap;
import java.util.Map;

/**
 * Entity representing chunked content from knowledge sources.
 * Stores processed text content with vector embeddings for semantic search.
 * Each chunk represents a portion of the original knowledge source content
 * optimized for AI retrieval and context injection.
 */
@Entity
@Table(name = "knowledge_chunk")
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
public class KnowledgeChunk extends AbstractAuditEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    public String id;

    /**
     * Parent knowledge source that this chunk belongs to.
     * Uses lazy loading to optimize performance when full knowledge details are not needed.
     */
    @Column(name = "knowledge_id", nullable = false)
    private String knowledgeId;

    /**
     * Sequential order of this chunk within the parent knowledge source.
     * Used to maintain original document structure and enable ordered retrieval.
     * Defaults to 0 for single-chunk knowledge sources.
     */
    @Column(name = "chunk_order", nullable = false)
    @Builder.Default
    private Integer chunkOrder = 0;

    /**
     * Text content of this knowledge chunk.
     * Stored as TEXT to accommodate large content blocks.
     * This is the actual content that will be used for AI context injection.
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * JSON metadata for storing chunk-specific information.
     * May include processing parameters, source location, confidence scores, etc.
     * Uses PostgreSQL JSONB for efficient storage and querying.
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb")
    @Builder.Default
    private Map<String, Object> metadata = new HashMap<>();

    /**
     * 768-dimensional vector embedding for semantic search.
     * Generated by smaller embedding models (e.g., sentence-transformers).
     * Null when embeddings haven't been generated or model doesn't support this dimension.
     */
    @Column(name = "embedding_768")
    @JdbcTypeCode(SqlTypes.VECTOR)
    private float[] embedding768;

    /**
     * 1536-dimensional vector embedding for semantic search.
     * Generated by larger embedding models (e.g., OpenAI text-embedding-ada-002).
     * Null when embeddings haven't been generated or model doesn't support this dimension.
     */
    @Column(name = "embedding_1536")
    @JdbcTypeCode(SqlTypes.VECTOR)
    private float[] embedding1536;

}
